# Generated by Django 5.0.6 on 2024-07-10 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_docidentificacao_pontoturistico_documentos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='documentos',
            new_name='doc_identificacao',
        ),
    ]
